package net.fnsco.service.dao.master;

import net.fnsco.service.domain.MerchantBank;
/**
 * @desc 商家银行卡信息DAO
 * @author tangliang
 * @date 2017年6月22日 下午3:09:29
 */
public interface MerchantBankDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_merchant_bank
     *
     * @mbggenerated Thu Jun 22 15:05:54 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_merchant_bank
     *
     * @mbggenerated Thu Jun 22 15:05:54 CST 2017
     */
    int insert(MerchantBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_merchant_bank
     *
     * @mbggenerated Thu Jun 22 15:05:54 CST 2017
     */
    int insertSelective(MerchantBank record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_merchant_bank
     *
     * @mbggenerated Thu Jun 22 15:05:54 CST 2017
     */
    MerchantBank selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_merchant_bank
     *
     * @mbggenerated Thu Jun 22 15:05:54 CST 2017
     */
    int updateByPrimaryKeySelective(MerchantBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_merchant_bank
     *
     * @mbggenerated Thu Jun 22 15:05:54 CST 2017
     */
    int updateByPrimaryKey(MerchantBank record);
}